config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check
  resources :countries, only: %i[home show] do
    resources :wishlists, only: %i[new create edit update destroy]
    resources :favourites, only: %i[new create edit update]
  end
  resources :favourites, only: %i[destroy]
  resources :wishlists, only: %i[destroy]
  get '/dashboard', to: 'countries#dashboard'
  post 'countries/:id/suggest_claude', to: 'countries#suggest_claude', as: :suggest_claude_country
  post 'countries/:id/suggest_season', to: 'countries#suggest_season', as: :suggest_season_country
  resources :continents, only: [:show]
  resources :regions, only: [:show]

  # Defines the root path route ("/")
  root 'countries#home'
end

app/models/country.rb
require 'httparty'

class Country < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search_by_name, against: [:name, :capital]

  has_many :country_photos, dependent: :destroy
  geocoded_by :address
  geocoded_by :capital_address
  after_validation :geocode, if: ->(obj) { obj.address.present? && obj.capital_address.present? }
  has_one :country_photo
  has_many_attached :photos
  has_many :favourites
  has_many :wishlists
  has_many :fans, through: :favourites, source: :user
  has_many :desirees, through: :wishlists, source: :user
  validates :name, :language_one, :continent, :flag_alt, :area, presence: true
  validates :flag, :timezone, :population, :latitude, :longitude, presence: true

  def address
    [latitude, longitude].compact.join(', ')
  end

  def capital_address
    [capital_latitude, capital_longitude].compact.join(', ')
  end

  def languages
    languages = []
    languages.push(language_one, language_two, language_three)
  end
end

# create this class so that I don't instantiate new Country instances every time
class UnsplashApi
  include HTTParty
  base_uri 'https://api.unsplash.com'

  def initialize(api_key)
    @headers = { "Authorization" => "Client-ID #{api_key}" }
  end

  # appends this to base uri
  def image_by_country(name)
    self.class.get("/search/photos", headers: @headers, query: { query: name, per_page: 1 })
  end
end

app/controllers/countries_controller.rb
require 'date'
require 'json'
require 'open-uri'

class CountriesController < ApplicationController
  include ActionView::Helpers::NumberHelper

  skip_before_action :authenticate_user!, only: %i[home show suggest_claude suggest_season]

  def home
    @continents = Country.select('continent').group('continent')
    countries = Country.all
    ids = []
    countries.each do |country|
      ids.push(country.id)
    end
    @random_country = ids.sample
    all_photos = CountryPhoto.all
    @photo = all_photos.sample
  end

  # show individual country
  def show
    @country = Country.find(params[:id])
    @user_wishlists = @country.wishlists.where(user_id: current_user)
    @user_favourites = @country.favourites.where(user_id: current_user)
    @favourite = Favourite.find_by(user_id: current_user, country_id: @country)
    @wishlist_already_created = Wishlist.exists?(user_id: current_user, country_id: @country)
    @favourite_already_created = Favourite.exists?(user_id: current_user, country_id: @country)
    @country_photo = CountryPhoto.find_by(country_id: @country)
    capital_address_marker
    currency_exchange_usd(@country)
  end

  def dashboard
    # left_outer_joins gets all records that have favourite, wishlists (like joins), then specify with where to filter
    @added_countries = Country.left_outer_joins(:favourites, :wishlists).where('favourites.user_id = ? OR wishlists.user_id = ?', current_user.id, current_user.id).distinct
    @user_wishlists = current_user.wishlists.count
    @user_favourites = current_user.favourites.count
  end

  def suggest_claude
    country = Country.find(params[:id])
    result = claude_suggestions(country.name)
    if result
      render json: { response: result }
    else
      return 'Claude is currently overloaded'
    end
  end

  def suggest_season
    country = Country.find(params[:id])
    result = seasonal_suggestions(country.name)
    if result
      render json: { response: result }
    else
      return 'Claude is currently overloaded'
    end
  end

  private

  def capital_address_marker
    @capital_markers = [{
        lat: @country.capital_latitude,
        lng: @country.capital_longitude,
        info_window_html: render_to_string(partial: 'shared/info_window_mapbox', locals: { country: @country })
      }]
  end

  def currency_exchange_usd(country)
    currency_code = country.currency_code
    url = "https://openexchangerates.org/api/latest.json?app_id=#{ENV.fetch('OPEN_EXCHANGE_APP_ID')}"
    currency_json = URI.parse(url).read
    all_currencies = JSON.parse(currency_json)
    base_country_rate = all_currencies['rates']["#{currency_code}"] || 'Not Found'
    uk_rate = all_currencies['rates']['GBP']
    country_rate = base_country_rate / uk_rate
    @country_rate = country_rate.round(3)
  end

  def claude_suggestions(country)
    claude = AiAgent.new.claude
    message =
      "Write 1 or 2 opening sentences about #{country} as a travel destination.
      Then, return a list of key attractions containing 5 popular tourist attractions as <ol> elements.
      Describe each attraction with 1 or 2 sentences. Don't ask any questions.
      Leave a <br> between the opening paragraph and the list."
    response = claude.messages(
      claude.user_message(message),
      { model: Claude::Model::CLAUDE_FASTEST }
    )
    AiAgent.new.format_claude_response(response)
  end

  def seasonal_suggestions(country)
    claude = AiAgent.new.claude
    message =
      "Write 1 or 2 opening sentences about the best time of year to visit #{country} as a travel destination.
      Then, return a list of other alternative times of year as <ol> elements.
      If a particular time of year is cheaper, mention it.
      Leave a <br> between the opening paragraph and the list."
    response = claude.messages(
      claude.user_message(message),
      { model: Claude::Model::CLAUDE_FASTEST }
    )
    AiAgent.new.format_claude_response(response)
  end
end

app/controllers/countrys_controller.rb
class CountrysController < ApplicationController
  # home, continents, show
  def home
    @continents = Country.select('continent').group('continent')
    # @africa = Country.where(continent: 'Africa')
    # @europe = Country.where(continent: 'Europe')
    # @asia = Country.where(continent: 'Asia')
    # @oceania = Country.where(continent: 'Oceania')
    # @north_america = Country.where(region: 'North America')
    # @central_america = Country.where(region: 'Central America')
    # @south_america = Country.where(region: 'South America')
  end

  # show individual country
  def show
    @country = Country.find(params[:id])
  end
end

app/helpers/countries_helper.rb
module CountriesHelper
  def population_index(country)
    countries = Country.where(continent: country.continent)
    populations = countries.map do |c|
      c.population
    end
    sorted = populations.sort.reverse
    index = sorted.find_index(country.population) + 1
    if country.population == sorted.first
      'This country has the largest population on the continent.'
    elsif country.population == sorted.last
      'This country has the smallest population on the continent.'
    elsif index.to_s.end_with?('1') && index != 1
      "This country has the #{index}st largest population on the continent."
    elsif index.to_s.end_with?('2')
      "This country has the #{index}nd largest population on the continent."
    elsif index.to_s.end_with?('3')
      "This country has the #{index}rd largest population on the continent."
    else
      "This country has the #{index}th largest population on the continent."
    end
  end

  def area_index(country)
    countries = Country.where(continent: country.continent)
    areas = countries.map do |c|
      c.area
    end
    sorted = areas.sort.reverse
    index = sorted.find_index(country.area) + 1
    if country.area == sorted.first
      'This country has the largest area on the continent.'
    elsif country.area == sorted.last
      'This country has the smallest area on the continent.'
    elsif index.to_s.end_with?('1') && index != 1
      "This country has the #{index}st largest area on the continent."
    elsif index.to_s.end_with?('2')
      "This country has the #{index}nd largest area on the continent."
    elsif index.to_s.end_with?('3')
      "This country has the #{index}rd largest area on the continent."
    else
      "This country has the #{index}th largest area on the continent."
    end
  end
end

app/views/countries/_button_to_continent.html.erb
<%= link_to continent_path(area) do %>
  <button class="continent-button"><%= area %></button>
<% end %>

app/views/countries/_button_to_region.html.erb
<%= link_to region_path(area) do %>
  <button class="continent-button"><%= area %></button>
<% end %>

app/views/countries/_delete_favourite.html.erb
<% country.favourites.each do |favourite| %>
  <%= button_to "Delete",
      favourite_path(favourite),
      method: :delete,
      data: { turbo_confirm: "Are you sure?" }
  %>
<% end %>

app/views/countries/_delete_wishlist.html.erb
<% country.wishlists.each do |wishlist| %>
  <%= button_to "Delete",
      wishlist_path(wishlist),
      method: :delete,
      data: { turbo_confirm: "Are you sure?" }
  %>
<% end %>

app/views/countries/dashboard.html.erb
<div class="dashboard container">
  <section>
    <h1 class="dashboard-header">Welcome to the Member's Area</h1>
    <div class="stats">
      <p>You have visited <%= @user_wishlists %> / <%= Country.count %> countries</p>
      <p>You'd like to visit <%= @user_favourites %> / <%= Country.count %> countries</p>
    </div>
    <div class="cards">
      <%= render "shared/continent_region_page", countries: @added_countries %>
    </div>
  </section>
</div>

app/views/countries/home.html.erb
<div class="home container" data-controller="scroll">
  <section class="banner">
    <% if @photo %>
      <div class="country-banner">
        <%= image_tag(@photo.image_url, alt: "#{@photo.image_alt}", class: "banner-image") %>
        <h1 class="page-header">The Country Club.</h1>
        <div class="banner-image-attributions">
          <p><%= @photo.country.name %></p>
          <p>
            Photo by
            <%= link_to @photo.photographer_name,
                "#{@photo.photographer_url}?utm_source=the_country_club&utm_medium=referral",
                target: '_blank',
                rel: 'noopener',
                class: "photographer-link" %>
            on
            <%= link_to 'Unsplash',
                'https://unsplash.com/?utm_source=the_country_club&utm_medium=referral',
                target: '_blank',
                rel: 'noopener',
                class: "photographer-link" %>
          </p>
        </div>
        <i class="fa-solid fa-chevron-down" data-action="click->scroll#scrollToFirstSection"></i>
      </div>
    <% end %>
  </section>

  <section class="home-info">
    <section class="introduction" data-scroll-target="firstSection">
      <h2 id="introduction">A travel tracker. <br> For the curious traveller.</h2>
      <ul class="introduction-text">
        <li>
          As someone who loves travelling and going down geography rabbit holes on Wikipedia, I built this app to
          merge these two interests together.
        </li>
        <li>
          Have your favourite countries and countries you want to visit all in one place.
        </li>
        <li>
          Be inspired by beautiful photos,
          courtesy of <a href="https://unsplash.com/?utm_source=the_country_club&utm_medium=referral" target="_blank">Unsplash</a>,
          and learn more about each country.
        </li>
        <li>
          Get suggestions from <a href="https://www.anthropic.com/claude">Claude</a> for activities and recommendations
          for the best time to visit.
        </li>
      </ul>
      <% if !user_signed_in? %>
        <%= link_to "Join the Club", new_user_registration_path, class: "btn" %>
      <% elsif %>
        <%= link_to "Member's Area", dashboard_path, class: "btn" %>
      <% end %>
    </section>

    <section class="info-box grid">
      <article class="info-box">
        <h3>Where Next?</h3>
        <ul>
          <li>Discover your next holiday destination</li>
          <li>Use AI to get activity suggestions and to find out when the best time to go is</li>
          <li>Choose a country and add it to your wishlist</li>
          <li>Rank how much you want to visit there</li>
        </ul>
      </article>

      <article class="info-box">
        <h3>Relive It.</h3>
        <ul>
          <li>Revisit your favourite countries by adding a country to your favourites</li>
          <li>Keep track of how many times you've visited, and when</li>
          <li>Add any notes about the country</li>
          <li>You can even upload any photos from your trip (in development)</li>
        </ul>
        <%# link %>
      </article>

      <article class="info-box">
        <h3>Be Curious.</h3>
        <ul>
          <li>Learn more about a particular country, as each country page has useful facts and figures</li>
          <li>Find out its capital and where its located</li>
          <li>Discover how small or large a country is, in terms of population</li>
          <li>Get your travel money organised by using the currency exchange tool (in development)</li>
        </ul>
        <%= link_to "Visit a random country", country_path(@random_country), class: "web-link" %>
        <%# <div class="info-box-container right-image"> %>
          <%#= image_tag("/images/be-curious.gif", alt: "gif showing website navigation of country page", class: "home-page-gif") %>
        <%# </div> %>
      </article>

      <article class="info-box">
        <%# <div class="info-box-container left-image"> %>
          <%#= image_tag("/images/react-weather.gif", alt: "React Weather app gif", class: "home-page-gif") %>
        <%# </div> %>
          <h3>Be Prepared.</h3>
          <ul>
            <li>Use my weather website to get the weather and some activity suggestions for a city you're visiting</li>
            <li>Search for a city (or even an area of a particular city) so that you're prepared for the day, whatever the weather may be</li>
            <li>If you're stuck for ideas, use AI to get some activity suggestions that are weather-appropriate</li>
          </ul>
          <%= link_to "Visit React Weather", "https://react-weather-claude-app-af1fc23c96a1.herokuapp.com/", target: "_blank", class: "web-link" %>
      </article>
    </section>
  </section>

  <footer>
    <p>
      All photos from Unsplash. No offence is meant to be caused by any of the photos.
    </p>
  </footer>
</div>

app/views/countries/show.html.erb
<%# Country show %>
<div class="country-page container">
  <% if @country_photo %>
    <section class="country-banner">
      <%= image_tag(@country_photo.image_url, alt: "#{@country_photo.image_alt}", class: "banner-image") %>
      <div class="banner-image-country-name">
        <h1><%= @country.name %></h1>
      </div>

      <div class="image-icons">
        <% case %>
        <% when @wishlist_already_created && @favourite_already_created %>
        <div class="icons">
          <div class="wishlist">
            <%= link_to edit_country_wishlist_path(@country) do %>
              <i class="fa-solid fa-paper-plane icon" alt="solid plane icon"></i>
            <% end %>
          </div>
          <div class="favourite">
            <%= link_to edit_country_favourite_path(@country) do %>
              <i class="fa-solid fa-heart icon" alt="solid heart icon"></i>
            <% end %>
          </div>
        </div>

        <% when @wishlist_already_created %>
        <div class="icons">
          <div class="wishlist">
            <%= link_to edit_country_wishlist_path(@country) do %>
              <i class="fa-solid fa-paper-plane icon" alt="solid plane icon"></i>
            <% end %>
          </div>
          <%= link_to new_country_favourite_path(@country) do %>
            <i class="fa-regular fa-heart icon" alt="empty heart icon"></i>
          <% end %>
        </div>

        <% when @favourite_already_created %>
        <div class="icons">
          <%= link_to new_country_wishlist_path(@country) do %>
            <i class="fa-regular fa-paper-plane icon" alt="empty plane icon"></i>
          <% end %>
          <div class="favourite">
            <%= link_to edit_country_favourite_path(@country) do %>
              <i class="fa-solid fa-heart icon" alt="solid heart icon"></i>
            <% end %>
          </div>
        </div>

        <% else %>
        <div class="icons">
          <%= link_to new_country_wishlist_path(@country) do %>
            <i class="fa-regular fa-paper-plane icon" alt="empty plane icon"></i>
          <% end %>
          <%= link_to new_country_favourite_path(@country) do %>
            <i class="fa-regular fa-heart icon" alt="empty heart icon"></i>
          <% end %>
        </div>
        <% end %>
      </div>

      <div class="banner-image-attributions">
        <p>
          Photo by
          <%= link_to @country_photo.photographer_name,
              "#{@country_photo.photographer_name}?utm_source=the_country_club&utm_medium=referral",
              target: '_blank', rel: 'noopener',
              class: "photographer-link" %>
          on
          <%= link_to 'Unsplash',
              'https://unsplash.com/?utm_source=the_country_club&utm_medium=referral',
              target: '_blank',
              rel: 'noopener',
              class: "photographer-link" %>
        </p>
      </div>
    </section>
  <% end %>

  <div
    class="ai-suggestion"
    data-controller="claude"
    data-claude-suggest-claude-url-value="<%= suggest_claude_country_path(@country) %>"
    data-claude-suggest-season-url-value="<%= suggest_season_country_path(@country) %>"
  >
    <div class="suggest-claude">
      <h2 class="ai-h2">What can I see and do in <%= @country.name %>?</h2>
      <button
        type="button"
        id="show-ai-button"
        data-claude-target="askClaudeButton"
        data-action="click->claude#showAi">
        Ask Claude
      </button>
      <div class="ai-text" data-claude-target="aiText"></div>
    </div>
    <div class="suggest-season">
      <h2 class="ai-h2">What is the best time of year to go?</h2>
      <button
        type="button"
        id="show-season-button"
        data-claude-target="seasonalButton"
        data-action="click->claude#seasonalSuggestion">
        Ask Claude
      </button>
      <div class="ai-text" data-claude-target="seasonalText"></div>
    </div>
  </div>

  <span class="dividing-line"></span>

  <section class="country-info">
    <h2>Information</h2>
    <div class="cards">
      <div class="country-info card">
        <%= image_tag(@country.flag, alt: @country.flag_alt, class: "individual-flag-image") %>
      </div>

      <%# <div class="country-card-info">
        <div class="clock" data-controller="clock">
          <div class="outer-clock-face">
            <div class="marking marking-one"></div>
            <div class="marking marking-two"></div>
            <div class="marking marking-three"></div>
            <div class="marking marking-four"></div>
          </div>
          <div class="inner-clock-face">
            <div class="hand hour-hand" data-clock-target="hourHand"></div>
            <div class="hand min-hand" data-clock-target="minsHand"></div>
            <div class="hand second-hand" data-clock-target="secondHand"></div>
          </div>
        </div>
        <div class="current-time">
          <%= Time.now.strftime('%B %e, %Y - %I:%M%P') %>
        <%# </div>
      </div> %>

      <div class="country-info card">
        <h3>Capital City</h3>
        <p><%= @country.capital %></p>
        <div class="mapbox-country"
          data-controller="map"
          data-map-markers-value="<%= @capital_markers.to_json %>"
          data-map-api-key-value="<%= ENV['MAPBOX_TOKEN_KEY'] %>">
        </div>
      </div>

      <div class="country-info card">
        <h3 class="show-card-title">Languages</h3>
        <% @country.languages.each do |language| %>
          <p><%= language unless language == "None" %></p>
        <% end %>
      </div>

      <div class="country-info card">
        <h3>Population</h3>
        <p><%= number_with_delimiter(@country.population, :delimiter => ',') %></p>
        <p><%= population_index(@country) %></p>
      </div>

      <div class="country-info card" data-controller="currency">
        <h3>Currency</h3>
        <p><%= "#{@country.currency} (#{@country.currency_code} / #{@country.currency_symbol})" %></p>
        <div class="user-input">
          <input type="text" placeholder="1" id="currency-input"> GBP = <%= "#{@country_rate} #{@country.currency_code}" %>
        </div>
        <p>(1 GBP = <%= "#{@country_rate} #{@country.currency_code}" %>)</p>
      </div>

      <div class="country-info card">
        <h3>Area</h3>
        <p><%= number_with_delimiter(@country.area, :delimiter => ',') %> km²</p>
        <p><%= area_index(@country) %></p>
      </div>
    </div>

  </section>

  <%# <span class="dividing-line"></span> %>

  <div class="favourite-photos">
  <% if user_signed_in? && @favourite_already_created %>
    <h2>Here are your photos from your trip</h2>
    <% @favourite.photos.each do |photo| %>
      <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
    <% end %>
  <% else %>
    <h2>Add a country to your favourites to add any photos from your trip</h2>
  <% end %>
  </div>

  <section class="cards-grid">
    <% case %>
    <% when @wishlist_already_created && @favourite_already_created %>
    <div class="wishlist card">
      <%= link_to edit_country_wishlist_path(@country), class: "list-link" do %>
        <i class="fa-solid fa-paper-plane icon" alt="solid plane icon"></i>
      <% end %>
      <%= render "delete_wishlist", country: @country %>
      <%= render "shared/wishlist_info", country: @country, wishlists: @user_wishlists %>
    </div>
    <div class="favourite card">
      <%= link_to edit_country_favourite_path(@country), class: "list-link" do %>
        <i class="fa-solid fa-heart icon" alt="solid heart icon"></i>
      <% end %>
      <%= render "delete_favourite", country: @country %>
      <%= render "shared/favourite_info", country: @country, favourites: @user_favourites %>
    </div>

    <% when @wishlist_already_created %>
    <div class="wishlist card">
      <%= link_to edit_country_wishlist_path(@country), class: "list-link" do %>
        <i class="fa-solid fa-paper-plane icon" alt="solid plane icon"></i>
      <% end %>
      <%= render "delete_wishlist", country: @country %>
      <%= render "shared/wishlist_info", country: @country, wishlists: @user_wishlists %>
    </div>
    <div class="favourite card">
      <%= link_to new_country_favourite_path(@country), class: "list-link" do %>
        <i class="fa-regular fa-heart icon" alt="empty heart icon"></i>
        <p>Add this country to your favourites if you've been here before.</p>
      <% end %>
    </div>

    <% when @favourite_already_created %>
    <div class="wishlist card">
      <%= link_to new_country_wishlist_path(@country), class: "list-link" do %>
        <i class="fa-regular fa-paper-plane icon" alt="empty plane icon"></i>
        <p>Add this country to your wishlist if you'd like to visit here.</p>
      <% end %>
    </div>
    <div class="favourite card">
      <%= link_to edit_country_favourite_path(@country), class: "list-link" do %>
        <i class="fa-solid fa-heart icon" alt="solid heart icon"></i>
      <% end %>
      <%= render "shared/favourite_info", country: @country, favourites: @user_favourites %>
      <%= render "delete_favourite", country: @country %>
    </div>

    <% else %>
    <div class="wishlist card">
      <%= link_to new_country_wishlist_path(@country), class: "list-link" do %>
        <i class="fa-regular fa-paper-plane icon" alt="empty plane icon"></i>
        <p>Add this country to your wishlist if you'd like to visit here.</p>
      <% end %>
    </div>
    <div class="favourite card">
      <%= link_to new_country_favourite_path(@country), class: "list-link" do %>
        <i class="fa-regular fa-heart icon" alt="empty heart icon"></i>
        <p>Add this country to your favourites if you've been here before.</p>
      <% end %>
    </div>
    <% end %>
  </section>
</div>